version: '3.7'
services:
  hp-back-end:
    build:
      context: .
      dockerfile: Dockerfile.node.dev
      args:
        - NODE_ENV=development
        - DATABASE_URL=postgresql://postgres:postgres@db:5432/my_app_db
        - DATABASE_URL_TEST=postgresql://postgres:postgres@db:5432/my_app_db_test
    volumes:
      - ./src:/usr/src/app/src
      - ./nodemon.json:/usr/src/app/nodemon.json
    ports:
      - '4000:4000'
    depends_on:
      - db
    healthcheck:
      disable: true
    command: npm run dev
  db:
    build:
      context: .
      dockerfile: Dockerfile.db.dev
    restart: always
    volumes:
      - ./db_dump:/var/lib/postgresql/data
    ports:
      - '15432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      start_period: 10s
      timeout: 4s
      retries: 3
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
